### ISSUE TITLE
AttributeError: mc_upload_only when running tee4mission_center.py

### ISSUE THREAD

**Issue by mrdthomas** [Celerium-Inc/tee4mission_center#30]
[commit:e9d84a0b284cadbaffc3807075a24f0eaaeae775](https://github.com/Celerium-Inc/tee4mission_center/commit/e9d84a0b284cadbaffc3807075a24f0eaaeae775)

It appears the change on line 36 is causing an error. **'mc_upload_only'** was changed to **'mc_only_upload'** and line 61 (if not FLAGS.mc_upload_only:) is expecting **'mc_upload_only'**.

(venv) $ python tee4mission_center.py --flagfile tee4mission_center.cfg  --debug=True

...

Traceback (most recent call last):
File "tee4mission_center.py", line 94, in
app.run(main)
File "/Users/OPSEC/Projects/TEE/venv/lib/python3.8/site-packages/absl/app.py", line 312, in run
_run_main(main, args)
File "/Users/OPSEC/Projects/TEE/venv/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
sys.exit(main(argv))
File "tee4mission_center.py", line 61, in main
if not FLAGS.mc_upload_only:
File "/Users/OPSEC/Projects/TEE/venv/lib/python3.8/site-packages/absl/flags/_flagvalues.py", line 481, in getattr
raise AttributeError(name)
**AttributeError: mc_upload_only**

**Comment by dandye** [comment]
Thank you for reporting this.  It is resolved in 7567c3f.
